AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app
    Sample SAM Template for sam-app
    

Resources:
   HttpFunctionStreamHandler:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
         CodeUri: target/demo-1.0.0.jar
         Handler: com.amazonaws.lambda.demo.LambdaFunctionStreamHandler::handleRequest
         Runtime: java8
         
   HttpFunctionRequestHandler:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
         CodeUri: target/demo-1.0.0.jar
         Handler: com.amazonaws.lambda.demo.LambdaFunctionRequestHandler::handleRequest
         Runtime: java8